    def analysis_custom_2(self, octfile, name, frontpts, backpts,
                     plotflag=False, accuracy='low', RGB=False, accelerad = False):
            """
            
            Edited version of analysis. Edited by ingebrh. The change is that
            the function takes in the full front and back sensor point strings
            that were previously created inside the analysis function, instead
            of the frontscan and backscan dictionaries.
            
            Changes from original analysis function:
                - Name changed from 'analysis' to 'analysis_custom_2'
                - Inputs 'frontscan' and 'backscan' replaced by 'frontpts'
                  and 'backpts'
                - Changed the call to _irrplot to _irrplot_custom
                - Added accelerad parameter for using accelerad or not in
                _irrplot_custom, and added description in docstring
            
            
            General analysis function, where linepts are passed in for calling the
            raytrace routine :py:class:`~bifacial_radiance.AnalysisObj._irrPlot` 
            and saved into results with 
            :py:class:`~bifacial_radiance.AnalysisObj._saveResults`.
    
            
            Parameters
            ------------
            octfile : string
                Filename and extension of .oct file
            name : string 
                Name to append to output files
            frontpts : string generated by analysisobj._linePtsMakeDict with
                       frontscan as input
            backtpts : string generated by analysisobj._linePtsMakeDict with
                       backscan as input
            plotflag : boolean
                Include plot of resulting irradiance
            accuracy : string 
                Either 'low' (default - faster) or 'high' (better for low light)
            RGB : Bool
                If the raytrace is a spectral raytrace and information for the three channe
                wants to be saved, set RGB to True.
            accelerad : Bool
                Use accelerad rtrace or not
    
                
            Returns
            -------
             File saved in `\\results\\irr_name.csv`
    
            """
    
            if octfile is None:
                print('Analysis aborted - no octfile \n')
                return None, None
            
            frontDict = self._irrPlot_custom(octfile, frontpts, name+'_Front',
                                        plotflag=plotflag, accuracy=accuracy,
                                        accelerad = accelerad)
    
            #bottom view.
            
            backDict = self._irrPlot_custom(octfile, backpts, name+'_Back',
                                       plotflag=plotflag, accuracy=accuracy,
                                       accelerad = accelerad)
           
            # don't save if _irrPlot returns an empty file.
            if frontDict is not None:
                if len(frontDict['Wm2']) != len(backDict['Wm2']):
                    self.Wm2Front = np.mean(frontDict['Wm2'])
                    self.Wm2Back = np.mean(backDict['Wm2'])
                    self.backRatio = self.Wm2Back / (self.Wm2Front + .001)
                    self._saveResults(frontDict, reardata=None, savefile='irr_%s.csv'%(name+'_Front'), RGB=RGB)
                    self._saveResults(data=None, reardata=backDict, savefile='irr_%s.csv'%(name+'_Back'), RGB=RGB)
                else:
                    self._saveResults(frontDict, backDict,'irr_%s.csv'%(name), RGB=RGB)
    
            return frontDict, backDict
